window.__ENV__ = {
  REPO_URL: "https://github.com/Phani-Raja-Bharath/IEEE_GeoAI_Course.git",
  PRE_SURVEY_URL: "https://YOUR_PRE_SURVEY_LINK_HERE",
  POST_SURVEY_URL: "https://YOUR_POST_SURVEY_LINK_HERE",
  WEEK_01_URL: "https://colab.research.google.com/github/Phani-Raja-Bharath/IEEE_GeoAI_Course/blob/main/Week_01/week01_course_setup_and_geoai_intro.ipynb",
  WEEK_02_URL: "https://colab.research.google.com/github/Phani-Raja-Bharath/IEEE_GeoAI_Course/blob/main/Week_02/week02_disaster_data_sources_and_visualization.ipynb",
  WEEK_03_URL: "https://colab.research.google.com/github/Phani-Raja-Bharath/IEEE_GeoAI_Course/blob/main/Week_03/week03_ml_cv_fundamentals_for_disaster_management.ipynb",
  WEEK_04_URL: "https://colab.research.google.com/github/Phani-Raja-Bharath/IEEE_GeoAI_Course/blob/main/Week_04/week04_surface_water_detection_with_segmentation.ipynb",
  WEEK_05_URL: "https://colab.research.google.com/github/Phani-Raja-Bharath/IEEE_GeoAI_Course/blob/main/Week_05/week05_vehicle_based_urban_flood_detection.ipynb",
  WEEK_06_URL: "https://colab.research.google.com/github/Phani-Raja-Bharath/IEEE_GeoAI_Course/blob/main/Week_06/week06_urban_flood_depth_estimation_pipeline.ipynb",
  WEEK_07_URL: "https://colab.research.google.com/github/Phani-Raja-Bharath/IEEE_GeoAI_Course/blob/main/Week_07/week07_model_evaluation_and_error_analysis.ipynb",
  WEEK_08_URL: "https://colab.research.google.com/github/Phani-Raja-Bharath/IEEE_GeoAI_Course/blob/main/Week_08/week08_disaster_response_decision_support.ipynb",
  WEEK_09_URL: "https://colab.research.google.com/github/Phani-Raja-Bharath/IEEE_GeoAI_Course/blob/main/Week_09/week09_urban_digital_twin_integration.ipynb",
  WEEK_10_URL: "https://colab.research.google.com/github/Phani-Raja-Bharath/IEEE_GeoAI_Course/blob/main/Week_10/week10_final_project_template.ipynb",
  RESEARCH_SURFACE_WATER_URL: "https://colab.research.google.com/github/Phani-Raja-Bharath/IEEE_GeoAI_Course/blob/main/research/surface_water_detection.ipynb",
  RESEARCH_URBAN_FLOOD_DEPTH_URL: "https://colab.research.google.com/github/Phani-Raja-Bharath/IEEE_GeoAI_Course/blob/main/research/urban_flood_depth.ipynb",
  FONTS_PRECONNECT_1: "https://fonts.googleapis.com",
  FONTS_PRECONNECT_2: "https://fonts.gstatic.com",
  FONTS_STYLESHEET: "https://fonts.googleapis.com/css2?family=Lora:wght@400;600;700&family=Inter:wght@400;500;600;700;800&display=swap"
};
